[package]
name = "oauth-blueprint-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
oauth-blueprint-lib = { path = "../oauth-blueprint-lib" }
blueprint-sdk = { path = "../../../crates/sdk", features = ["std", "tangle-evm"] }
tokio = { version = "^1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
serde_json = "1"
oauth-blueprint-lib = { path = "../oauth-blueprint-lib" }
