[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["dependencies"]
auto_detect_remappings = false
solc = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200

# Use soldeer-managed dependencies
remappings = [
    "@tnt-core/=dependencies/tnt-core-0.10.4/src/",
    "@openzeppelin/contracts/=dependencies/tnt-core-0.10.4/dependencies/@openzeppelin-contracts-5.1.0/",
    "forge-std/=dependencies/tnt-core-0.10.4/dependencies/forge-std-1.9.4/src/"
]

[soldeer]
recursive_deps = true
remappings_location = "txt"
remappings_version = false

[dependencies]
tnt-core = "0.10.4"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
