[package]
name = "apikey-blueprint-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
apikey-blueprint-lib = { path = "../apikey-blueprint-lib" }
blueprint-sdk = { path = "../../../crates/sdk", features = ["std", "tangle"] }
tokio = { version = "^1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
serde_json = "1"
apikey-blueprint-lib = { path = "../apikey-blueprint-lib" }

[lints]
workspace = true
